### ISSUE TITLE
Curl https://api commerce.coinbase.com/

### ISSUE THREAD

**Issue by Annasadra** [coinbase/coinbase-commerce-python#18]
1.curl https:// api commerce.coin base.com /checkouts\
2.-H"X-CC-Api-Key:
3.<4e300ee11-e0e9-45b4-b3d4-16be-b6166b92>

**Comment by oa-coinbase** [comment]
Hi there, looks like this issue might have been opened by mistake? Closing it now but feel free to ask the community any questions you may have.
