### ISSUE TITLE
Ethereum

### ISSUE THREAD

**Issue by Annasadra** [coinbase/coinbase-commerce-python#19]
1."hosted_ur1":http://commerce.coinbase.com/charges\
2."time":"2020.03.01T13:35Z"
3."status":"new"
4."metadata":{}
5."payments":[0,5,]
6."adresses":{0xAcCfC8b51C709525AA6Fc87D9a4150Fc16B58Ee2

**Comment by Annasadra** [comment]
1."hosted_ur1":"http://commerce.coinbase.com/charges/66BEOV2A"
2."time":"2020.03.01T13:50Z"
3."status":"new"
4."metadata":{}
5."payments"[0.5]
6."adresses":{0xAcCfC8b51C709525AA6Fc87D9a4150Fc16B58Ee2
7."0x419f91df39951fd4e8acc8f1874b01c0c78ceba6"
8.         }
9.      }
10. }

**Comment by Annasadra** [comment]
1."hosted_ur1":"http://commerce.coinbase.com/charges/66BEOV2A"
2."time":"2020.03.01T13:50Z"
3."status":"new"
4."metadata":{}
5."payments"[0.5]
6."adresses":{0xAcCfC8b51C709525AA6Fc87D9a4150Fc16B58Ee2
7."0x419f91df39951fd4e8acc8f1874b01c0c78ceba6"
8.         }
9.      }
10. }

**Comment by Annasadra** [comment]
1."requested_info=["Anna Samoilova","annasadra@outlook.com"])

**Comment by Annasadra** [comment]
1."requested_info=["Anna Samoilova","annasadra@outlook.com"])

**Comment by oa-coinbase** [comment]
@Annasadra Hi there, looks like this issue might have been opened by mistake? Closing it now but feel free to ask the community any questions you may have.
